# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: ccguyka
#google_analytics: ccguyka
title: ccguyka

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: ccguyka

description: Stylish Jekyll Theme
author:
  name: ccguyka
  email: ccguyka@gmail.com
  github: ccguyka
  bitbucket: ccguyka
  twitter: ccguyka
  bio: Your stylish, minimalist theme!
  email_md5: 7e8a9390de5bb7e7f841876141754956

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH: https://ccguyka.github.io/blog

gems:
  - jekyll-paginate
